name: Build DuyKhanhOS IMG

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir output
          URL=$(gh release view \
            --repo InfiniteMagazine228/DuyKhanhOS-Version-5 \
            --json assets \
            -q '.assets[] | select(.name|endswith(".iso")) | .url' | head -1)

          wget \
            --header="Authorization: Bearer $GH_TOKEN" \
            --header="Accept: application/octet-stream" \
            "$URL" \
            -O output/DuyKhanhOS.iso

      - name: Create IMG
        run: |
          cp output/DuyKhanhOS.iso output/DuyKhanhOS.img

      - name: SHA256
        run: |
          sha256sum output/DuyKhanhOS.iso > output/DuyKhanhOS.iso.sha256
          sha256sum output/DuyKhanhOS.img > output/DuyKhanhOS.img.sha256

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DuyKhanhOS
          path: output/*

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-build
          files: |
            output/DuyKhanhOS.iso
            output/DuyKhanhOS.img
            output/DuyKhanhOS.iso.sha256
            output/DuyKhanhOS.img.sha256
